### ISSUE TITLE
lager is missing as a dependency

### ISSUE THREAD

**Issue by tverlaan** [travelping/exometer_influxdb#21]
Lager is missing as a dependency in rebar.config. I wanted to create a PR directly but I'm not sure how you would like to resolve this (since I also see a 'use_hut' branch). Are you okay with fetching lager from hex.pm? Or do you want to pull it from github?

I'm using `mix` which currently can't resolve the dependencies correctly which causes compilation to fail.

Ps. Are you interested in publishing this package on hex? I would gladly create a PR.

**Comment by surik** [comment]
Which revision of exometer_core do you use?

**Comment by tverlaan** [comment]
Good question! I'm using a newer version apparently. Switching to the older version indeed solves the dep problem. Thanks!

Is there a reason not to support newer versions of exometer_core? AFAICT adding lager as a dependency is all it would need.

**Comment by surik** [comment]
We don't use a newer version because it is not ready. See https://github.com/Feuerlabs/exometer_core/issues/57

**Comment by tverlaan** [comment]
I see. Thanks again!
Closing.
