### ISSUE TITLE
integer / float type error with histogram

### ISSUE THREAD

**Issue by tverlaan** [travelping/exometer_influxdb#22]
I have created a subscription for influxdb to a histogram. On initialisation the histogram gives back all floats:

``` elixir
{:ok,
 [{:n, 0.0}, {:mean, 0.0}, {:min, 0.0}, {:max, 0.0}, {:median, 0.0}, {50, 0.0},
  {75, 0.0}, {90, 0.0}, {95, 0.0}, {99, 0.0}, {999, 0.0}]}
```

All values will be reported as float to influxdb. After sending some values some numbers are represented as integers:

``` elixir
{:ok,
 [{:n, 3}, {:mean, 192.397}, {:min, 192.397}, {:max, 192.397}, {:median, 192},
  {50, 192.397}, {75, 192.397}, {90, 192.397}, {95, 192.397}, {99, 192.397},
  {999, 192.397}]}
```

This results in an error because the reporter detects values when they're being send and there is now a mismatch, see:

```
14:56:38.771 [warning] InfluxDB reporter got unexpected response with code 400 and body: <<"{\"error\":\"write failed: field type conflict: input field \\\"n\\\" on measurement \\\"ecto_query_exec_time\\\" is type int64, already exists as type float\"}\n">>. Reconnecting ...
```

 I didn't see an option to configure this. I think histograms (because of their initial value) should always be floats. Is this desirable and what should the configuration for it look like? I can invest some time in this and create a PR, but it would be nice to know in which direction it should go.

**Comment by GalaxyGorilla** [comment]
This is in fact a very interesting discovery! The crucial line in exometer is this:

https://github.com/Feuerlabs/exometer_core/blob/6bdd642a3eccc0da8fe556efcb7a2134ee865da0/src/exometer_histogram.erl#L291

Are you sure that the error really happens after some values are sent? Because this behaviour is rather not consistent. I would expect that the median is _always_ an integer. EDIT: How did you retrieve those values? Just via get_value/1?

**Comment by tverlaan** [comment]
It is in fact not only the median. It is also the number `:n` (which should be an int anyway, right?).

This metric is predefined so everything is sent to influxdb straight away. After I do a query (using ecto) the histogram is updated and values are changing. At that point I start receiving errors from the influxdb reporter which then reconnects on every error.

I retrieved the values with get_value/1 yes.

**Comment by GalaxyGorilla** [comment]
As a workaround the histogram truncation option might help. Did you try to use it?

**Comment by tverlaan** [comment]
My original setting was `truncate: false`. Now with truncate removed it is true by default and I don't have the issue. Thanks for sorting that out.

So technically this would need to be solved in exometer, correct?

**Comment by GalaxyGorilla** [comment]
Imho exometer shouldn't return different types on the same datapoint. This is quite easy to fix here in the reporter but I see this as an issue for exometer too. But anyway, some feature would be nice in the reporter to format numeric data to integer or floats - regardless of what exometer does.

**Comment by surik** [comment]
Hi @tverlaan,

I close it for now because it looks more related to exometer.
