### ISSUE TITLE
Remove lager as a dependency

### ISSUE THREAD

**Issue by mootpointer** [travelping/exometer_influxdb#26]
Lager is no longer a dependency of `exometer_core`. It would be great to remove it from `exometer_influxdb` as well.

Is there anything internal which is requiring lager as the logger instead something like `hut` which the core project has moved to?

**Comment by surik** [comment]
Hi @mootpointer. 

Honestly this issue a little bit worrying me, see #21 and #25. I would like to get rid of `lager` and use the latest `exometer_core` with `hut` but I don't know how I can build exometer_core as a dependency with `lager` support. If you give me some hint I will be very grateful.

**Comment by mootpointer** [comment]
I don't use lager personally I'm presently using Elixir, so Elixir.Logger picks things up from sasl, so I'm not really in a position to be able to make this work.

**Comment by surik** [comment]
Yes, it is because `hut` uses `sasl` by default. But what if I want to use it with `lager`?

In my personal opinion I would just have `sasl` support in `exometer_core` and `exometer_influxdb`(without `hut`) because it is compatible with `lager` and Elixir `logger`. We may try to go this way.

**Comment by mootpointer** [comment]
Forcing lager as a dependency in something like `exometer_core` or
`exometer_influxdb` seems like an anti-pattern.

**Comment by surik** [comment]
See #27
