### ISSUE TITLE
Blank out password when logging connection successful info statement

### ISSUE THREAD

**Issue by ianwalter** [travelping/exometer_influxdb#28]
I don't think the password should be leaked to the logs:

```
14:56:39.781 [info] InfluxDB reporter connecting success: [{autosubscribe,true},{protocol,https},{host,<<"influxdb.domain.com">>},{username,<<"admin">>},{password,<<"mypasswordishere">>},{port,8086},{db,<<"dev">>},{tags,[]}]
```

https://github.com/travelping/exometer_influxdb/blob/master/src/exometer_report_influxdb.erl#L108

**Comment by surik** [comment]
Of course, we can blank it but looks `exometer_core` will log all options (and password too) in some case: https://github.com/Feuerlabs/exometer_core/blob/master/src/exometer_report.erl#L664
