### ISSUE TITLE
Can't get exometer_influxdb to work with predefined metrics

### ISSUE THREAD

**Issue by ianwalter** [travelping/exometer_influxdb#30]
A few of us have been getting an error like:

```
[warning] InfluxDB reporter got trouble when looking [erlang,memory] metric's tag: not_found
```

You can see the discussion within the comments of this post:
http://milhouseonsoftware.com/2016/05/08/measuring-your-elixir-application/

It seems the metric lookup isn't working. Disabling it as @jbavari has done here seems to be a work around:
https://github.com/jbavari/exometer_influxdb/commit/f14d592ebe5edef1826faec2815dc54c49d5988d

I'm sorry I'm not familiar with Erlang enough to really understand how to fix this.

**Comment by GalaxyGorilla** [comment]
We also use predefined metrics in production (erlang and elixir) and never really had this issue. One example is [here](https://github.com/xerions/metricman/blob/master/config/config.exs#L7). At the provided link you can also see an example how to get the erlang beam memory usage via predefined metrics. Maybe this already helps because your predefined metrics are possibly not initialized properly. However, we do not use elixometer, we use exometer_core directly (which could also be a reason).

**Comment by ianwalter** [comment]
I was able to get this working by specifying `subscribe_options: [{:tag, []}]` in the elixometer config, but I think this should be considered a bug since you shouldn't have to specify a tag.

**Comment by GalaxyGorilla** [comment]
Can you check if [this commit](https://github.com/pinterest/elixometer/commit/d9adc56d845f9d8cfff581a8c91b201442ab8d87) from elixometer fixes your problem? But yea, we should provide e.g. a log when those options are malformed.

**Comment by ianwalter** [comment]
That fixed it, thanks.

**Comment by ianwalter** [comment]
Actually, I think the change to Elixometer only fixed this for metrics created through Elixometer, the original problem was for the metric defined as:

``` elixir
memory_stats = ~w(atom binary ets processes total)a
config :exometer_core,
  predefined: [
    {
      ~w(erlang memory)a,
      {:function, :erlang, :memory, [], :proplist, memory_stats},
      []
    }
  ],
  report: [
    reporters: [
      exometer_report_influxdb: [
        protocol: :https,
        host: "myhost",
        username: System.get_env("INFLUXDB_USER"),
        password: System.get_env("INFLUXDB_PASS"),
        port: 8086,
        db: "metrics"
      ]
    ],
    subscribers: [
      {
        :exometer_report_influxdb,
        [:erlang, :memory], memory_stats, 1_000, true
      }
    ]
  ]
```

It doesn't seem to matter if I change `true` to `[]` in `[:erlang, :memory], memory_stats, 1_000, true` or if I add a list of tags, I still get the original error above.

**Comment by surik** [comment]
@ianwalter Is it possible to create some simple Elixir application to reproduce this issue? Could you do?

**Comment by ianwalter** [comment]
@surik Sure, check out this branch: https://github.com/ianwalter/hackney_metrics/tree/exometer_influxdb
(**note:** I'm using the master branch to reproduce a different issue)

Also, `exometer_influxdb` is configured for the prod environment.

**Comment by surik** [comment]
Looks  that `elixometer` depends on some `exometer_core` from hex.pm but it doesn't contain some commits like [changing start phases](https://github.com/Feuerlabs/exometer_core/commit/6a87e9d156dc631250c184c19b9f055ec69c58c6) which I guess will fix your issue.

**Comment by ianwalter** [comment]
You're right, there must have been a different issue when I tried the latest, thanks for looking into this!
