### ISSUE TITLE
dependency mismatch - rebar3 & hex?

### ISSUE THREAD

**Issue by tverlaan** [travelping/exometer_influxdb#41]
We have a dependency mismatch which could be solved by using hackney from hex.pm in this project. It would require moving to rebar3 as far as I understand. Would you be open to using rebar3 and pointing to hex.pm instead of repo on github on branch master? I can create a PR in that case.

We used `override: true` in our config but would like to remove that again.

```
Dependencies have diverged:
* hackney (Hex package)
  the dependency hackney in deps/httpoison/mix.exs is overriding a child dependency:

  > In deps/httpoison/mix.exs:
    {:hackney, "~> 1.8.0", [env: :prod, hex: "hackney", repo: "hexpm", optional: false, manager: :rebar3]}

  > In deps/exometer_influxdb/rebar.config:
    {:hackney, ~r/.*/, [env: :prod, git: "git://github.com/benoitc/hackney.git", branch: "master", manager: :rebar]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies
```

**Comment by surik** [comment]
We are ok with using rebar3 and hex but I'm not sure that the proper version of exometer_core available on hex.

**Comment by tverlaan** [comment]
afaik exometer is not on hex yet, but we can still reference github for exometer until that happens.

**Comment by tverlaan** [comment]
Please see PR #42

**Comment by tverlaan** [comment]
Closing this in favor of PR
